/**
 * The launcher entry points: Camoufox(), NewBrowser(), NewContext().
 *
 * TypeScript twin of python/src/sync_api.py + async_api.py. The Python
 * library ships both a sync and an async variant because Playwright-Python has
 * two APIs; playwright-core has only one (promise-based), so the two collapse
 * into this single module.
 */

import { Impit } from "impit";
import {
	type Browser,
	type BrowserContext,
	type BrowserType,
	firefox,
} from "playwright-core";
import { generateContextFingerprint, type Preset } from "./fingerprints.js";
import { type ProxyConfig, ProxyHelper } from "./ip.js";
import {
	applyNoViewport,
	attachNoViewportDefault,
	attachVirtualDisplay,
	type LaunchOptions,
	launchOptions,
	spoofsWindowDimensions,
} from "./utils.js";
import { VirtualDisplay } from "./virtdisplay.js";

export type Headless = boolean | "virtual";

export interface NewBrowserOptions extends Omit<LaunchOptions, "headless"> {
	/** Whether to run the browser headless. On Linux, `"virtual"` runs a real
	 * (non-headless) browser on an Xvfb display instead. */
	headless?: Headless;
	/** A set of launch options generated by `launchOptions()` to use as-is. */
	from_options?: Record<string, any>;
	/** Whether to use a persistent context. */
	persistent_context?: boolean;
	/** Directory for the persistent profile. Implies `persistent_context`. */
	user_data_dir?: string;
}

/**
 * Launches a Camoufox browser and returns it. Close it with `browser.close()`;
 * a virtual display, if one was spawned, is torn down with it.
 *
 * ```ts
 * const browser = await Camoufox({ headless: true });
 * const page = await browser.newPage();
 * ```
 */
export async function Camoufox(
	options: NewBrowserOptions & { persistent_context: true },
): Promise<BrowserContext>;
export async function Camoufox(
	options: NewBrowserOptions & { user_data_dir: string },
): Promise<BrowserContext>;
export async function Camoufox(options?: NewBrowserOptions): Promise<Browser>;
export async function Camoufox(
	options: NewBrowserOptions = {},
): Promise<Browser | BrowserContext> {
	return NewBrowser(firefox, options);
}

/**
 * Launches a new browser instance for Camoufox given a set of launch options.
 */
export async function NewBrowser(
	playwright: BrowserType,
	options: NewBrowserOptions & { persistent_context: true },
): Promise<BrowserContext>;
export async function NewBrowser(
	playwright: BrowserType,
	options: NewBrowserOptions & { user_data_dir: string },
): Promise<BrowserContext>;
export async function NewBrowser(
	playwright: BrowserType,
	options?: NewBrowserOptions,
): Promise<Browser>;
export async function NewBrowser(
	playwright: BrowserType,
	{
		headless,
		from_options,
		persistent_context,
		user_data_dir,
		debug,
		...kwargs
	}: NewBrowserOptions = {},
): Promise<Browser | BrowserContext> {
	let virtualDisplay: VirtualDisplay | null = null;
	let headlessBool: boolean | undefined;

	if (headless === "virtual") {
		virtualDisplay = new VirtualDisplay(debug ?? false);
		kwargs.virtual_display = await virtualDisplay.get();
		headlessBool = false;
	} else {
		headlessBool = headless;
	}

	let fromOptions = from_options;
	try {
		if (!fromOptions) {
			fromOptions = await launchOptions({
				...kwargs,
				headless: headlessBool,
				debug,
			});
		}
	} catch (error) {
		// A failed launch must not leave the Xvfb process behind.
		virtualDisplay?.kill();
		throw error;
	}

	// Playwright's default viewport deadlocks Juggler when the window is spoofed
	// to a different size (daijro/camoufox#666), so default to no viewport.
	const noViewportDefault = spoofsWindowDimensions(fromOptions);

	try {
		// Persistent context
		if (persistent_context || user_data_dir !== undefined) {
			const { userDataDir: _ignored, ...rest } = fromOptions;
			let contextOptions: Record<string, any> = { ...rest };
			if (noViewportDefault) {
				contextOptions = applyNoViewport(contextOptions);
			}
			const context = await playwright.launchPersistentContext(
				user_data_dir ?? "",
				contextOptions,
			);
			return attachVirtualDisplay(context, virtualDisplay);
		}

		// Browser
		const browser = await playwright.launch(fromOptions);
		if (noViewportDefault) {
			attachNoViewportDefault(browser);
		}
		return attachVirtualDisplay(browser, virtualDisplay);
	} catch (error) {
		virtualDisplay?.kill();
		throw error;
	}
}

export interface NewContextOptions extends Record<string, any> {
	/** A specific fingerprint preset to use. If omitted, one is picked at random
	 * (or BrowserForge generates a synthetic identity). */
	preset?: Preset;
	/** Target OS for preset selection ("windows", "macos", "linux"). */
	os?: string;
	/** Firefox version string for UA patching. */
	ff_version?: string;
	/** IPv4 address to spoof for WebRTC ICE candidates. */
	webrtc_ip?: string;
	/** Per-context proxy, in Playwright's format. */
	proxy?: ProxyConfig;
	/** Per-context geolocation. */
	geolocation?: { latitude: number; longitude: number; accuracy?: number };
}

/** Builds a proxy URL string with embedded credentials. */
function proxyUrlWithCreds(proxy: ProxyConfig): string {
	const { schema, url, port } = ProxyHelper.parseServer(proxy.server);
	if (proxy.username && proxy.password) {
		const host = port ? `${url}:${port}` : url;
		return `${schema}://${proxy.username}:${proxy.password}@${host}`;
	}
	return proxy.server;
}

/** Queries ip-api.com through the proxy for the exit IP and timezone. */
async function resolveProxyGeo(
	proxy: ProxyConfig,
): Promise<{ ip: string | null; timezone: string | null }> {
	try {
		const impit = new Impit({
			proxyUrl: proxyUrlWithCreds(proxy),
			timeout: 10_000,
		});
		const resp = await impit.fetch(
			"http://ip-api.com/json?fields=query,timezone",
		);
		const data = (await resp.json()) as { query?: string; timezone?: string };
		return { ip: data.query || null, timezone: data.timezone || null };
	} catch {
		return { ip: null, timezone: null };
	}
}

/**
 * Creates a new browser context with a unique fingerprint identity.
 *
 * Each context gets its own fingerprint with unique seeds for audio, canvas,
 * and font-spacing noise. All values are applied via addInitScript so they
 * self-destruct before page scripts can detect them.
 */
export async function NewContext(
	browser: Browser,
	{
		preset,
		os,
		ff_version,
		webrtc_ip,
		proxy,
		geolocation,
		...contextOptions
	}: NewContextOptions = {},
): Promise<BrowserContext> {
	// Auto-derive the WebRTC IP and timezone from the proxy's exit IP when they
	// aren't explicitly provided.
	let webrtcIp = webrtc_ip;
	if (proxy && (!webrtcIp || !("timezoneId" in contextOptions))) {
		const geo = await resolveProxyGeo(proxy);
		if (!webrtcIp) webrtcIp = geo.ip ?? undefined;
		if (!("timezoneId" in contextOptions) && geo.timezone) {
			contextOptions.timezoneId = geo.timezone;
		}
	}

	const fp = await generateContextFingerprint({
		preset,
		os,
		ff_version,
		webrtc_ip: webrtcIp,
	});

	// Merge the generated context options with caller overrides (caller wins)
	const opts: Record<string, any> = {
		...fp.context_options,
		...contextOptions,
	};
	if (proxy) opts.proxy = proxy;
	if (geolocation) {
		opts.geolocation = geolocation;
		opts.permissions ??= ["geolocation"];
	}

	const context = await browser.newContext(opts);
	await context.addInitScript(fp.init_script);
	return context;
}
